apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs
spec:
  selector:
    app: nginx-nfs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to ClusterIP or LoadBalancer as needed

